apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cr-peer0
  namespace: cr-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cr-peer0
  chart:
    git: git@github.com:rahultoraskarr/blockchain-automation-framework.git
    ref: new_test220
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: cr-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.18
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.cr-net:7051
      gossipexternalendpoint: peer0.cr-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443
      localmspid: crMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: cr-user

    storage:
      peer:
        storageclassname: crsc
        storagesize: 512Mi
      couchdb:
        storageclassname: crsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: cr-net-auth
      secretprefix: secret/crypto/peerOrganizations/cr-net/peers/peer0.cr-net
      secretambassador: secret/crypto/peerOrganizations/cr-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/cr-net/couchdb/cr?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: haproxy
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
