apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mr-peer1
  namespace: mr-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mr-peer1
  chart:
    git: git@github.com:rahultoraskarr/blockchain-automation-framework.git
    ref: new_test220
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: mr-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.18
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer1
      gossippeeraddress: peer1.mr-net:70511
      gossipexternalendpoint: peer1.mr-net.hf.dev2.aws.blockchaincloudpoc-develop.com:8443:8443
      localmspid: mrMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: mr-user

    storage:
      peer:
        storageclassname: mrsc
        storagesize: 512Mi
      couchdb:
        storageclassname: mrsc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: mr-net-auth
      secretprefix: secret/crypto/peerOrganizations/mr-net/peers/peer1.mr-net
      secretambassador: secret/crypto/peerOrganizations/mr-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/mr-net/couchdb/mr?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: haproxy
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com:8443
